device:           
local_rank:
world_size:
global_rank:
save_dir:

train_cfg: # train base params
    project:          aicity_test
    teacher_model:    yzf_csp #torch_wp_base #ids_visible_universal_middle_bn #gaussian_yolov3 #torch_wp_base #yolo_asff #poly_test #torch_wp_base #yolof #tsh_csp #swin # #v5_wp_city_fpn.yaml #torch_wp_base
    student_model:    csp_test
    teacher_weights:  /home/yu/workspace/yoloall/yoloall/runs_det/distiller/yologfl/teacher.pth #固定teacher模型
    student_weights:  /home/yu/workspace/yoloall/yoloall/runs_det/distiller/yologfl/last_stud.pth #
    freeze:           []
    quantize:         false

    version:          yolo-gfl-mmdet #yolo-gfl-mmdet #yolo-fcos-mmdet #yolo-center-mmdet #yolo-atss-yzf-mmdet #gaussian_v3 # v3 / v5 / v4 / yolo-mmdet / yolof-mmdet / yolox-mmdet / yolox-yzf-mmdet / yolo-atss-mmdet / yolo-atss-yzf-mmdet
    anchors:          [[8,8], [16,16], [32, 32]]
    #[[17,8,  10,14,  26,12,  16,23,  49,15],[31,25,  26,43,  59,27,  46,58,  107,31],[76,51,  138,57,  98,90,  203,82,  411,127]]
    #[[11,11,  26,10,  19,21,  41,17,  26,37], [68,23,  42,41,  74,36,  54,66,  124,39], [85,86,  151,65,  198,102,  297,82,  280,208]]
    #yolo-center-mmdet -> poly_test
    #yolox-mmdet, yolo-fcos-mmdet, yolo-gfl-mmdet, [[8,8], [16,16], [32, 32]] 
    #yolof, poly_yolo: [[11,11, 26,37, 74,36, 124,39, 198,102, 280,208]] #单层输出 区别：yolof用深层特征、poly_yolo用特征图最大特征

    width:            960
    height:           576
    multi_scale:      false
    quad:             false

    epochs:           300
    batch_size:       8
    nbs:              64
    total_batch_size: 
    workers:          1
    sync_bn:          true

    test:             true
    evolve:           false
    save_model_items: 10 #每隔多少轮保存一次模型
    name:             exp
    save_tmp_model:   true
    debug:            0 # show datasets

    logiter:          1

two_stage:
    two_stage_enabel: 0
    roi_extract:      RoIAlign # RoIAlign | RoIPool
    model:            normal
    feat_channels:    256
    loss_mean:        true
    start:            3 # more than 3

transformer:
    transformer_enabl:      0
    transformer_cfg:
        embed_dims:         96
        depths:             [2, 2, 18, 2]
        num_heads:          [3, 6, 12, 24]
        window_size:        7
        mlp_ratio:          4
        qkv_bias:           True
        qk_scale: 
        drop_rate:          0.0
        attn_drop_rate:     0.0
        drop_path_rate:     0.2
        patch_norm:         True
        out_indices:        [0, 1, 2, 3]
        with_cp:            False
        convert_weights:    True
        pretrained:         '/home/yu/data/premodel/swin_small_patch4_window7_224.pth'

    optimizer_cfg:  
        lr:             0.001 #源码中为0.0001
        betas:          [0.9, 0.999]
        weight_decay:   0.05

    paramwise_cfg:
        absolute_pos_embed: 
            decay_mult: 0.0
        norm: 
            decay_mult: 0.0 
        relative_position_bias_table: 
            decay_mult: 0.0

distiller:
    distill_enable:     true
    #FGD: #《Focal and Global Knowledge Distillation for Detectors》 Feature Transfer / 离线蒸馏 (anchor_base 已经测试完毕)  
    distill_method:     'ld' #'fgd'、'ld'
    teacher_init:       false
    #'fgd'
    fgd_param:
        distill_cfg:
            temp:           0.5 #0.8
            alpha_fgd:      0.00002 #0.0016
            beta_fgd:       0.00002 #0.0008
            gamma_fgd:      0.00002 #0.0008
            lambda_fgd:     0.0000002 #0.000008
        distill_start:      -1 #设置开始蒸馏的epoch
        distill_step:       [20,25,30,50]
    #'ld'
    ld_param:
        loss_ld_reduction:   'mean'
        loss_ld_weight:       0.25
        loss_ld_T:            10


video: # video detect params
    minbatch:         1000
    samplestep:       15
    history:          10
    hid_size:         64
    in_conv_k:        3
    hid_conv_k:       1
    hid_norm:         True
    circle_mean_num:  5
    init:             False
    act:              tanh

data:
    train:              /home/yu/data/dataset/coco/val_label.txt
    val:                /home/yu/data/dataset/coco/test_label.txt
    nc:                 80
    iou_thres:          0.35

    name_conf_cls_map:  [
        ['person', 0.3, [0]], 
        ['bicycle', 0.3, [1]], 
        ['car', 0.3, [2]], 
        ['motorcycle', 0.3, [3]], 
        ['airplane', 0.3, [4]], 
        ['bus', 0.3, [5]], 
        ['train', 0.3, [6]], 
        ['truck', 0.3, [7]], 
        ['boat', 0.3, [8]], 
        ['traffic light', 0.3, [9]], 
        ['fire hydrant', 0.3, [10]], 
        ['stop sign', 0.3, [11]], 
        ['parking meter', 0.3, [12]], 
        ['bench', 0.3, [13]], 
        ['bird', 0.3, [14]], 
        ['cat', 0.3, [15]], 
        ['dog', 0.3, [16]], 
        ['horse', 0.3, [17]], 
        ['sheep', 0.3, [18]], 
        ['cow', 0.3, [19]], 
        ['elephant', 0.3, [20]], 
        ['bear', 0.3, [21]], 
        ['zebra', 0.3, [22]], 
        ['giraffe', 0.3, [23]], 
        ['backpack', 0.3, [24]], 
        ['umbrella', 0.3, [25]], 
        ['handbag', 0.3, [26]], 
        ['tie', 0.3, [27]], 
        ['suitcase', 0.3, [28]], 
        ['frisbee', 0.3, [29]], 
        ['skis', 0.3, [30]], 
        ['snowboard', 0.3, [31]], 
        ['sports ball', 0.3, [32]], 
        ['kite', 0.3, [33]], 
        ['baseball bat', 0.3, [34]], 
        ['baseball glove', 0.3, [35]], 
        ['skateboard', 0.3, [36]], 
        ['surfboard', 0.3, [37]], 
        ['tennis racket', 0.3, [38]], 
        ['bottle', 0.3, [39]], 
        ['wine glass', 0.3, [40]], 
        ['cup', 0.3, [41]], 
        ['fork', 0.3, [42]], 
        ['knife', 0.3, [43]], 
        ['spoon', 0.3, [44]], 
        ['bowl', 0.3, [45]], 
        ['banana', 0.3, [46]], 
        ['apple', 0.3, [47]], 
        ['sandwich', 0.3, [48]], 
        ['orange', 0.3, [49]], 
        ['broccoli', 0.3, [50]], 
        ['carrot', 0.3, [51]], 
        ['hot dog', 0.3, [52]], 
        ['pizza', 0.3, [53]], 
        ['donut', 0.3, [54]], 
        ['cake', 0.3, [55]], 
        ['chair', 0.3, [56]], 
        ['couch', 0.3, [57]], 
        ['potted plant', 0.3, [58]], 
        ['bed', 0.3, [59]], 
        ['dining table', 0.3, [60]], 
        ['toilet', 0.3, [61]], 
        ['tv', 0.3, [62]], 
        ['laptop', 0.3, [63]], 
        ['mouse', 0.3, [64]], 
        ['remote', 0.3, [65]], 
        ['keyboard', 0.3, [66]], 
        ['cell phone', 0.3, [67]], 
        ['microwave', 0.3, [68]], 
        ['oven', 0.3, [69]], 
        ['toaster', 0.3, [70]], 
        ['sink', 0.3, [71]], 
        ['refrigerator', 0.3, [72]], 
        ['book', 0.3, [73]], 
        ['clock', 0.3, [74]], 
        ['vase', 0.3, [75]], 
        ['scissors', 0.3, [76]], 
        ['teddy bear', 0.3, [77]], 
        ['hair drier', 0.3, [78]], 
        ['toothbrush', 0.3, [79]]
    ]

        

yolommdet: # yolo mmdet loss params
    loss_mean:         true
    loss_cls_weight:   1.0
    loss_conf_weight:  1.0
    loss_xy_weight:    0.75
    loss_wh_weight:    0.75
    loss_reduction:    sum
    pos_iou_thr:       0.5
    neg_iou_thr:       0.5
    show_pos_bbox:     false
    area_scale:        true
    mmdet_obj_scale:   1.5
    mmdet_noobj_scale: 1.0
    box_loss_type:     'ciou'  # 'mse | ciou | iou'
    loss_iou_weight:   4.0  # use in iou loss

yolofmmdet: #yolof mmdet loss param
    loss_mean:         true
    loss_cls_weight:   1.0
    loss_conf_weight:  1.0
    loss_xy_weight:    0.75
    loss_wh_weight:    0.75
    loss_reduction:    sum
    pos_ignore_thr:    0.15 # use
    neg_ignore_thr:    0.8  # use (原论文为大于0.7,小于0.15设为忽略的样本目标)
    show_pos_bbox:     false
    area_scale:        true
    mmdet_obj_scale:   1.5
    mmdet_noobj_scale: 1.0
    box_loss_type:     'ciou'  # 'mse | ciou'
    loss_iou_weight:   4.0  # use in iou loss

yoloxmmdet: #yolox loss params
    loss_mean:          true
    loss_cls_weight:    1.0
    loss_conf_weight:   1.0
    loss_reduction:     sum
    max_norm:           0
    max_one_norm:       0
    show_pos_bbox:      false
    area_scale:         true
    mmdet_obj_scale:    1.5
    mmdet_noobj_scale:  1.0
    box_loss_type:      'iou'  # 'mse | ciou'
    loss_iou_weight:    5.0  # use in iou loss
    simOTA:
        center_radius:  2.5 
        candidate_topk: 10 
        iou_weight:     3.0
        cls_weight:     1.0

yzfmmdet: #yzf loss params
    loss_mean:         true
    loss_cls_weight:   1.0
    loss_conf_weight:  1.0
    loss_xy_weight:    0.75
    loss_wh_weight:    0.75
    loss_reduction:    sum
    pos_iou_thr:       0.5
    neg_iou_thr:       0.5
    show_pos_bbox:     false
    area_scale:        true
    mmdet_obj_scale:   1.5
    mmdet_noobj_scale: 1.0
    box_loss_type:     'iou'  # 'mse | ciou'
    loss_iou_weight:   4.0  # use in iou loss
    simOTA:
        center_radius:  2.5 #2.5 
        candidate_topk: 10 
        iou_weight:     3.0
        cls_weight:     1.0

yoloatss:
    loss_mean:         true
    loss_cls_weight:   1.0
    loss_conf_weight:  1.0
    loss_xy_weight:    0.75
    loss_wh_weight:    0.75
    loss_reduction:    sum
    topk:              9
    show_pos_bbox:     false
    area_scale:        true
    mmdet_obj_scale:   1.5
    mmdet_noobj_scale: 1.0
    box_loss_type:     'ciou'  # 'mse | ciou'
    loss_iou_weight:   4.0  # use in iou loss       

yoloatssyzf:

yolofcos:
    loss_mean:         true
    loss_cls_weight:   1.0
    loss_conf_weight:  1.0
    loss_reduction:    mean
    max_norm:          0
    max_one_norm:      0
    show_pos_bbox:     false
    area_scale:        true
    mmdet_obj_scale:   1.5
    mmdet_noobj_scale: 1.0
    box_loss_type:     'ciou'  # 'mse | ciou'
    loss_iou_weight:   4.0  # use in iou loss  
    regress_ranges:    [[-1, 128], [128, 256], [256, 960]]
    center_sampling:   true #true表示中心点采样
    center_sample_radius: 1.5
    norm_on_bbox:       true #表示gt_box在各个特征图层上归一化gt框来和预测框的做损失的。
    centerness_on_reg:  false #true表示中心度在从回归的特征分支上卷积、false表示中心度从分类的特征分支上上卷积获取

yolocenter:
    loss_weight_heatmap:    1
    loss_wh_weight:         0.1
    loss_offset_weight:     1
    show_pos_bbox:          false

yologfl:
    loss_mean:         true
    loss_cls_weight:   1.0
    loss_iou_weight:   4.0
    loss_dfl_weight:   0.25
    loss_reduction:    mean
    box_loss_type:     'ciou'  # 'mse | ciou'
    use_sigmoid:       false #True 走Gfcoal_v1 False 走Gfcoal_v2
    reg_max:           16 #Gfcoal_v1
    reg_topk:          4  #Gfcoal_v2
    add_mean:          true #Gfcoal_v2
    topk:              9
    show_pos_bbox:     false
    area_scale:        true
    mmdet_obj_scale:   1.5
    mmdet_noobj_scale: 1.0

yolov3v5: # yolov3/v5 loss params
    box:               0.01
    cls:               0.5
    cls_pw:            1.0
    obj:               1.0
    obj_pw:            1.0
    iou_t:             0.2
    anchor_t:          2.91 # 4
    fl_gamma:          0.0
    loss_mean:         true
    autobalance:       false
    v5_loss_balance:   false
    targets_jklm:      false
    objness_iou_ratio: 0.0
    warmup_bias_lr:    0.1
    gaussian_thresh:   0.3

yolov3gaussian:

yolov4: # yolov4 loss params
    use_all_anchors:   false
    object_scale:      1.0
    noobject_scale:    1.0
    class_scale:       1.0
    coord_scale:       1.0
    cls_normalizer:    1.0
    iou_normalizer:    1.0
    ignore_thresh:     0.5
    iou_thresh:        1.0
    label_smooth_eps:  0
    box_loss_type:     ciou
    focalloss:         false

hyp: # hyp
    adam:            False
    norm:            L2
    max_norm:        0
    max_one_norm:    0

    lr0:             0.001 #0.001
    lrf:             0.2
    momentum:        0.9
    weight_decay:    0.0001 #mmdet的 'weight_decay': 0.0001
    warmup_epochs:   3.0
    warmup_momentum: 0.9
    warmup_bias_lr:  0.0 #该参数仅在v5，v3版本中有效其他为0

    lr_cos:          false
    lr_step:         [150, 300, 100000]

    hsv_h:           0.1
    hsv_s:           0.5 #0.5
    hsv_v:           0.5 #0.5
    degrees:         0.0
    translate:       0.0
    scale:           0.0
    shear:           0.0
    perspective:     0.0
    flipud:          0.0
    fliplr:          0.0
    mosaic:          0.0
    mixup:           0.0
    gaussianblur:    0.0
    cutcolor:        0.0
    cutout:          0.0


version_info:
    yolov3:                 yolov3v5
    yolov5:                 yolov3v5
    yolov4:                 yolov4
    yolo-mmdet:             yolommdet
    yolov3-gaussian:        yolov3gaussian
    yolof-mmdet:            yolofmmdet 
    yolox-mmdet:            yoloxmmdet
    yolox-yzf-mmdet:        yzfmmdet
    yolo-atss-mmdet:        yoloatss
    yolo-atss-yzf-mmdet:    yoloatssyzf  
    yolo-fcos-mmdet:        yolofcos   
    yolo-center-mmdet:      yolocenter
    yolo-gfl-mmdet:         yologfl