device:
local_rank:
world_size:
global_rank:
save_dir:

train_cfg:
    project:            coco_test
    model:              yzf_csp #wp_base #
    weight:             
    weight_two:         
    freeze:             []
    version:            mmdet
    anchors:            [[10,13, 16,30, 33,23],[30,61, 62,45, 59,119],[116,90, 156,198, 373,326]]
    width:              960
    height:             576
    multi_scale:        false
    quad:               false

    epochs:             300
    batch_size:         2
    nbs:                64
    total_batch_size:   
    workers:            1
    sync_bn:            true
    test:               true
    evolve:             false

    name:               exp2
    save_temp_model:    true
    debug:              0
    logiter:            1

two_stage:
    two_stage_enabel:   0
    roi_extract:        RoIAIign #RoIAIign | RoIPool
    model:              normal
    feat_channels:      256
    loss_mean:          true
    start:              3

data:
    train:              /home/yu/data/dataset/coco/val_label.txt
    val:                /home/yu/data/dataset/coco/test_label.txt
    nc:                 80
    iou_thres:          0.35

    name_conf_cls_map:  [
        ['person', 0.3, [0]], 
        ['bicycle', 0.3, [1]], 
        ['car', 0.3, [2]], 
        ['motorcycle', 0.3, [3]], 
        ['airplane', 0.3, [4]], 
        ['bus', 0.3, [5]], 
        ['train', 0.3, [6]], 
        ['truck', 0.3, [7]], 
        ['boat', 0.3, [8]], 
        ['traffic light', 0.3, [9]], 
        ['fire hydrant', 0.3, [10]], 
        ['stop sign', 0.3, [11]], 
        ['parking meter', 0.3, [12]], 
        ['bench', 0.3, [13]], 
        ['bird', 0.3, [14]], 
        ['cat', 0.3, [15]], 
        ['dog', 0.3, [16]], 
        ['horse', 0.3, [17]], 
        ['sheep', 0.3, [18]], 
        ['cow', 0.3, [19]], 
        ['elephant', 0.3, [20]], 
        ['bear', 0.3, [21]], 
        ['zebra', 0.3, [22]], 
        ['giraffe', 0.3, [23]], 
        ['backpack', 0.3, [24]], 
        ['umbrella', 0.3, [25]], 
        ['handbag', 0.3, [26]], 
        ['tie', 0.3, [27]], 
        ['suitcase', 0.3, [28]], 
        ['frisbee', 0.3, [29]], 
        ['skis', 0.3, [30]], 
        ['snowboard', 0.3, [31]], 
        ['sports ball', 0.3, [32]], 
        ['kite', 0.3, [33]], 
        ['baseball bat', 0.3, [34]], 
        ['baseball glove', 0.3, [35]], 
        ['skateboard', 0.3, [36]], 
        ['surfboard', 0.3, [37]], 
        ['tennis racket', 0.3, [38]], 
        ['bottle', 0.3, [39]], 
        ['wine glass', 0.3, [40]], 
        ['cup', 0.3, [41]], 
        ['fork', 0.3, [42]], 
        ['knife', 0.3, [43]], 
        ['spoon', 0.3, [44]], 
        ['bowl', 0.3, [45]], 
        ['banana', 0.3, [46]], 
        ['apple', 0.3, [47]], 
        ['sandwich', 0.3, [48]], 
        ['orange', 0.3, [49]], 
        ['broccoli', 0.3, [50]], 
        ['carrot', 0.3, [51]], 
        ['hot dog', 0.3, [52]], 
        ['pizza', 0.3, [53]], 
        ['donut', 0.3, [54]], 
        ['cake', 0.3, [55]], 
        ['chair', 0.3, [56]], 
        ['couch', 0.3, [57]], 
        ['potted plant', 0.3, [58]], 
        ['bed', 0.3, [59]], 
        ['dining table', 0.3, [60]], 
        ['toilet', 0.3, [61]], 
        ['tv', 0.3, [62]], 
        ['laptop', 0.3, [63]], 
        ['mouse', 0.3, [64]], 
        ['remote', 0.3, [65]], 
        ['keyboard', 0.3, [66]], 
        ['cell phone', 0.3, [67]], 
        ['microwave', 0.3, [68]], 
        ['oven', 0.3, [69]], 
        ['toaster', 0.3, [70]], 
        ['sink', 0.3, [71]], 
        ['refrigerator', 0.3, [72]], 
        ['book', 0.3, [73]], 
        ['clock', 0.3, [74]], 
        ['vase', 0.3, [75]], 
        ['scissors', 0.3, [76]], 
        ['teddy bear', 0.3, [77]], 
        ['hair drier', 0.3, [78]], 
        ['toothbrush', 0.3, [79]]
    ]

yolommdet:
    loss_mean:          true
    loss_cls_weight:    1.0
    loss_conf_weight:   1.0
    loss_xy_weight:     0.75
    loss_wh_weight:     0.75
    loss_reduction:     sum
    pos_iou_thr:        0.5
    neg_iou_thr:        0.5
    max_norm:           0
    max_one_norm:       0
    show_pos_bbox:      false
    area_scale:         true
    mmdet_obj_scale:    1.5
    mmdet_noobj_scale:  1.0
    box_loss_type:      'ciou'  # 'mse' | 'ciou'
    loss_iou_weight:    4.0

yolov3v5:
    box:                0.01
    cls:                0.5
    cls_pw:             1.0
    obj:                1.0
    obj_pw:             1.0
    iou_t:              0.2
    anchor_t:           4
    fl_gamma:           0.0
    loss_mean:          true
    autobanlance:       false
    v5_loss_balance:    false
    targets_jklm:       false
    objness_iou_ratio:  0.0
    warmup_bias_lr:     0.1

yolov4:
    use_all_anchors:    false
    object_scale:       1.0
    noobject_scale:     1.0
    class_scale:        1.0
    coord_scale:        1.0
    cls_normalizer:     1.0
    iou_normalizer:     1.0
    ignore_thresh:      0.5
    iou_thresh:         1.0
    label_smooth_eps:   0
    box_loss_type:      ciou
    focalloss:          false

hyp:
    adam:               false
    norm:               L2

    lr0:                0.001
    lrf:                0.2
    momentum:           0.9
    weight_decay:       0.0005
    warmup_epochs:      3.0
    warmup_momentum:    0.9
    warmup_bias_lr:     0.0
    lr_cos:             true
    lr_step:            [100,200,1000000]
    hsv_h:              0.1
    hsv_s:              0.5
    hsv_v:              0.5
    degrees:            0.0
    translate:          0.1
    scale:              0.5
    shear:              0.0
    perspective:        0.0
    flipup:             0.0
    fliplr:             0.2
    mosaic:             0.0
    mixup:              0.0
    gaussianblur:       0.2
    cutcolor:           0.1
    cutout:             0.0


version_info:
    yolov3:                 yolov3v5
    yolov5:                 yolov3v5
    yolov4:                 yolov4
    yolo-mmdet:             yolommdet
    yolov3-gaussian:        yolov3gaussian
    yolof-mmdet:            yolofmmdet 
    yolox-mmdet:            yoloxmmdet
    yolox-yzf-mmdet:        yzfmmdet
    yolo-atss-mmdet:        yoloatss
    yolo-atss-yzf-mmdet:    yoloatssyzf  
    yolo-fcos-mmdet:        yolofcos   
    yolo-center-mmdet:      yolocenter
    yolo-gfl-mmdet:         yologfl







