project:          plant
data_dir: 
    train:        /home/yu/data/kaggle_data/cvpr2020-plant-pathology-master/data/train.txt
    test:         /home/yu/data/kaggle_data/cvpr2020-plant-pathology-master/data/test.txt 
dataset:          list
class_map:
    healthy':           0 
    multiple_diseases:  1
    rust:               2 
    scab:               3
model:            res_net
model_cfg:
    layer_num:    18
resume:
num_classes:      4
input_size:       [3,224,224]
crop_pct:         1
batch_size:       16
mean:
std:        
opt:              sgd
momentum:         0.9
weight_decay:     0.00002
lr:               0.05
warmup_lr:        0.0001
epochs:           300
warmup-epochs:    3
