project:          imagenet
data_dir:         
dataset:          DCL
class_map:
    cat:  0
    dog:  1
model:            resnet50
resume:
num_classes:      1000
input_size:       [3,224,224]
crop_pct:         1
mean:
std:        
opt:              sgd
momentum:         0.9
weight_decay:     0.00002
lr:               0.05
warmup_lr:        0.0001
epochs:           300
warmup-epochs:    3
