config: config/base.py
local_rank: -1
train_cfg:
  data: data_demo
  version: mmdet
  cfg: yolov5s.yaml
  weights: ''
  anchors:
  - - 10
    - 13
    - 16
    - 30
    - 33
    - 23
  - - 30
    - 61
    - 62
    - 45
    - 59
    - 119
  - - 116
    - 90
    - 156
    - 198
    - 373
    - 326
  epochs: 300
  batch_size: 8
  hight: 640
  width: 640
  step:
  - 8
  - 16
  - 32
  rect: false
  resume: false
  nosave: false
  notest: false
  project: runs/train
  name: exp
  workers: 1
  noautoanchor: true
  evolve: false
  bucket: ''
  cache_images: false
  image_weights: false
  device: ''
  multi_scale: false
  single_cls: false
  adam: false
  sync_bn: false
  log_imgs: 16
  log_artifacts: false
  exist_ok: false
  debug: 0
hyp:
  lr0: 0.001
  lrf: 0.2
  momentum: 0.9
  weight_decay: 0.0005
  warmup_epochs: 2.0
  warmup_momentum: 0.9
  warmup_bias_lr: 0.0
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
data:
  data_type: COCO
  train_path: /home/yu/workspace/yoloall/yoloall/val_data.txt
  val_path: /home/yu/workspace/yoloall/yoloall/val_data.txt
  test_path: ''
  nc: 80
  names:
  - person
  - bicycle
  - car
  - motorcycle
  - airplane
  - bus
  - train
  - truck
  - boat
  - traffic light
  - fire hydrant
  - stop sign
  - parking meter
  - bench
  - bird
  - cat
  - dog
  - horse
  - sheep
  - cow
  - elephant
  - bear
  - zebra
  - giraffe
  - backpack
  - umbrella
  - handbag
  - tie
  - suitcase
  - frisbee
  - skis
  - snowboard
  - sports ball
  - kite
  - baseball bat
  - baseball glove
  - skateboard
  - surfboard
  - tennis racket
  - bottle
  - wine glass
  - cup
  - fork
  - knife
  - spoon
  - bowl
  - banana
  - apple
  - sandwich
  - orange
  - broccoli
  - carrot
  - hot dog
  - pizza
  - donut
  - cake
  - chair
  - couch
  - potted plant
  - bed
  - dining table
  - toilet
  - tv
  - laptop
  - mouse
  - remote
  - keyboard
  - cell phone
  - microwave
  - oven
  - toaster
  - sink
  - refrigerator
  - book
  - clock
  - vase
  - scissors
  - teddy bear
  - hair drier
  - toothbrush
  cls_map:
    0:
    - 1
    1:
    - 2
    2:
    - 3
    3:
    - 4
    4:
    - 5
    5:
    - 6
    6:
    - 7
    7:
    - 8
    8:
    - 9
    9:
    - 10
    10:
    - 11
    11:
    - 13
    12:
    - 14
    13:
    - 15
    14:
    - 16
    15:
    - 17
    16:
    - 18
    17:
    - 19
    18:
    - 20
    19:
    - 21
    20:
    - 22
    21:
    - 23
    22:
    - 24
    23:
    - 25
    24:
    - 27
    25:
    - 28
    26:
    - 31
    27:
    - 32
    28:
    - 33
    29:
    - 34
    30:
    - 35
    31:
    - 36
    32:
    - 37
    33:
    - 38
    34:
    - 39
    35:
    - 40
    36:
    - 41
    37:
    - 42
    38:
    - 43
    39:
    - 44
    40:
    - 46
    41:
    - 47
    42:
    - 48
    43:
    - 49
    44:
    - 50
    45:
    - 51
    46:
    - 52
    47:
    - 53
    48:
    - 54
    49:
    - 55
    50:
    - 56
    51:
    - 57
    52:
    - 58
    53:
    - 59
    54:
    - 60
    55:
    - 61
    56:
    - 62
    57:
    - 63
    58:
    - 64
    59:
    - 65
    60:
    - 67
    61:
    - 70
    62:
    - 72
    63:
    - 73
    64:
    - 74
    65:
    - 75
    66:
    - 76
    67:
    - 77
    68:
    - 78
    69:
    - 79
    70:
    - 80
    71:
    - 81
    72:
    - 82
    73:
    - 84
    74:
    - 85
    75:
    - 86
    76:
    - 87
    77:
    - 88
    78:
    - 89
    79:
    - 90
  iou_thres:
  - 0.3
  nms_thres:
  - 0.3
total_batch_size: 8
world_size: 1
global_rank: -1
img_size:
- 640
- 640
name: exp
save_dir: runs/train/exp11
