config: config/base.yaml
local_rank: -1
device: null
world_size: 1
global_rank: -1
save_dir: run_det/coco_test_yzf_csp_mmdet/exp2
train_cfg:
  project: coco_test
  model: yzf_csp
  weight: null
  weight_two: null
  freeze: []
  version: mmdet
  anchors:
  - - 10
    - 13
    - 16
    - 30
    - 33
    - 23
  - - 30
    - 61
    - 62
    - 45
    - 59
    - 119
  - - 116
    - 90
    - 156
    - 198
    - 373
    - 326
  width: 960
  height: 576
  multi_scale: false
  quad: false
  epochs: 300
  batch_size: 2
  nbs: 64
  total_batch_size: null
  workers: 1
  sync_bn: true
  test: true
  evolve: false
  name: exp2
  save_temp_model: true
  debug: 0
  logiter: 1
two_stage:
  two_stage_enabel: 0
  roi_extract: RoIAIign
  model: normal
  feat_channels: 256
  loss_mean: true
  start: 3
data:
  train: /home/yu/data/dataset/coco/val_label.txt
  val: /home/yu/data/dataset/coco/test_label.txt
  nc: 80
  iou_thres: 0.35
  name_conf_cls_map:
  - - person
    - 0.3
    - &id001
      - 0
  - - bicycle
    - 0.3
    - &id002
      - 1
  - - car
    - 0.3
    - &id003
      - 2
  - - motorcycle
    - 0.3
    - &id004
      - 3
  - - airplane
    - 0.3
    - &id005
      - 4
  - - bus
    - 0.3
    - &id006
      - 5
  - - train
    - 0.3
    - &id007
      - 6
  - - truck
    - 0.3
    - &id008
      - 7
  - - boat
    - 0.3
    - &id009
      - 8
  - - traffic light
    - 0.3
    - &id010
      - 9
  - - fire hydrant
    - 0.3
    - &id011
      - 10
  - - stop sign
    - 0.3
    - &id012
      - 11
  - - parking meter
    - 0.3
    - &id013
      - 12
  - - bench
    - 0.3
    - &id014
      - 13
  - - bird
    - 0.3
    - &id015
      - 14
  - - cat
    - 0.3
    - &id016
      - 15
  - - dog
    - 0.3
    - &id017
      - 16
  - - horse
    - 0.3
    - &id018
      - 17
  - - sheep
    - 0.3
    - &id019
      - 18
  - - cow
    - 0.3
    - &id020
      - 19
  - - elephant
    - 0.3
    - &id021
      - 20
  - - bear
    - 0.3
    - &id022
      - 21
  - - zebra
    - 0.3
    - &id023
      - 22
  - - giraffe
    - 0.3
    - &id024
      - 23
  - - backpack
    - 0.3
    - &id025
      - 24
  - - umbrella
    - 0.3
    - &id026
      - 25
  - - handbag
    - 0.3
    - &id027
      - 26
  - - tie
    - 0.3
    - &id028
      - 27
  - - suitcase
    - 0.3
    - &id029
      - 28
  - - frisbee
    - 0.3
    - &id030
      - 29
  - - skis
    - 0.3
    - &id031
      - 30
  - - snowboard
    - 0.3
    - &id032
      - 31
  - - sports ball
    - 0.3
    - &id033
      - 32
  - - kite
    - 0.3
    - &id034
      - 33
  - - baseball bat
    - 0.3
    - &id035
      - 34
  - - baseball glove
    - 0.3
    - &id036
      - 35
  - - skateboard
    - 0.3
    - &id037
      - 36
  - - surfboard
    - 0.3
    - &id038
      - 37
  - - tennis racket
    - 0.3
    - &id039
      - 38
  - - bottle
    - 0.3
    - &id040
      - 39
  - - wine glass
    - 0.3
    - &id041
      - 40
  - - cup
    - 0.3
    - &id042
      - 41
  - - fork
    - 0.3
    - &id043
      - 42
  - - knife
    - 0.3
    - &id044
      - 43
  - - spoon
    - 0.3
    - &id045
      - 44
  - - bowl
    - 0.3
    - &id046
      - 45
  - - banana
    - 0.3
    - &id047
      - 46
  - - apple
    - 0.3
    - &id048
      - 47
  - - sandwich
    - 0.3
    - &id049
      - 48
  - - orange
    - 0.3
    - &id050
      - 49
  - - broccoli
    - 0.3
    - &id051
      - 50
  - - carrot
    - 0.3
    - &id052
      - 51
  - - hot dog
    - 0.3
    - &id053
      - 52
  - - pizza
    - 0.3
    - &id054
      - 53
  - - donut
    - 0.3
    - &id055
      - 54
  - - cake
    - 0.3
    - &id056
      - 55
  - - chair
    - 0.3
    - &id057
      - 56
  - - couch
    - 0.3
    - &id058
      - 57
  - - potted plant
    - 0.3
    - &id059
      - 58
  - - bed
    - 0.3
    - &id060
      - 59
  - - dining table
    - 0.3
    - &id061
      - 60
  - - toilet
    - 0.3
    - &id062
      - 61
  - - tv
    - 0.3
    - &id063
      - 62
  - - laptop
    - 0.3
    - &id064
      - 63
  - - mouse
    - 0.3
    - &id065
      - 64
  - - remote
    - 0.3
    - &id066
      - 65
  - - keyboard
    - 0.3
    - &id067
      - 66
  - - cell phone
    - 0.3
    - &id068
      - 67
  - - microwave
    - 0.3
    - &id069
      - 68
  - - oven
    - 0.3
    - &id070
      - 69
  - - toaster
    - 0.3
    - &id071
      - 70
  - - sink
    - 0.3
    - &id072
      - 71
  - - refrigerator
    - 0.3
    - &id073
      - 72
  - - book
    - 0.3
    - &id074
      - 73
  - - clock
    - 0.3
    - &id075
      - 74
  - - vase
    - 0.3
    - &id076
      - 75
  - - scissors
    - 0.3
    - &id077
      - 76
  - - teddy bear
    - 0.3
    - &id078
      - 77
  - - hair drier
    - 0.3
    - &id079
      - 78
  - - toothbrush
    - 0.3
    - &id080
      - 79
  names:
  - person
  - bicycle
  - car
  - motorcycle
  - airplane
  - bus
  - train
  - truck
  - boat
  - traffic light
  - fire hydrant
  - stop sign
  - parking meter
  - bench
  - bird
  - cat
  - dog
  - horse
  - sheep
  - cow
  - elephant
  - bear
  - zebra
  - giraffe
  - backpack
  - umbrella
  - handbag
  - tie
  - suitcase
  - frisbee
  - skis
  - snowboard
  - sports ball
  - kite
  - baseball bat
  - baseball glove
  - skateboard
  - surfboard
  - tennis racket
  - bottle
  - wine glass
  - cup
  - fork
  - knife
  - spoon
  - bowl
  - banana
  - apple
  - sandwich
  - orange
  - broccoli
  - carrot
  - hot dog
  - pizza
  - donut
  - cake
  - chair
  - couch
  - potted plant
  - bed
  - dining table
  - toilet
  - tv
  - laptop
  - mouse
  - remote
  - keyboard
  - cell phone
  - microwave
  - oven
  - toaster
  - sink
  - refrigerator
  - book
  - clock
  - vase
  - scissors
  - teddy bear
  - hair drier
  - toothbrush
  conf_thres:
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  cls_map:
  - *id001
  - *id002
  - *id003
  - *id004
  - *id005
  - *id006
  - *id007
  - *id008
  - *id009
  - *id010
  - *id011
  - *id012
  - *id013
  - *id014
  - *id015
  - *id016
  - *id017
  - *id018
  - *id019
  - *id020
  - *id021
  - *id022
  - *id023
  - *id024
  - *id025
  - *id026
  - *id027
  - *id028
  - *id029
  - *id030
  - *id031
  - *id032
  - *id033
  - *id034
  - *id035
  - *id036
  - *id037
  - *id038
  - *id039
  - *id040
  - *id041
  - *id042
  - *id043
  - *id044
  - *id045
  - *id046
  - *id047
  - *id048
  - *id049
  - *id050
  - *id051
  - *id052
  - *id053
  - *id054
  - *id055
  - *id056
  - *id057
  - *id058
  - *id059
  - *id060
  - *id061
  - *id062
  - *id063
  - *id064
  - *id065
  - *id066
  - *id067
  - *id068
  - *id069
  - *id070
  - *id071
  - *id072
  - *id073
  - *id074
  - *id075
  - *id076
  - *id077
  - *id078
  - *id079
  - *id080
  version: mmdet
yolommdet:
  loss_mean: true
  loss_cls_weight: 1.0
  loss_conf_weight: 1.0
  loss_xy_weight: 0.75
  loss_wh_weight: 0.75
  loss_reduction: sum
  pos_iou_thr: 0.5
  neg_iou_thr: 0.5
  max_norm: 0
  max_one_norm: 0
  show_pos_bbox: false
  area_scale: true
  mmdet_obj_scale: 1.5
  mmdet_noobj_scale: 1.0
  box_loss_type: ciou
  loss_iou_weight: 4.0
yolov3v5:
  box: 0.01
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4
  fl_gamma: 0.0
  loss_mean: true
  autobanlance: false
  v5_loss_balance: false
  targets_jklm: false
  objness_iou_ratio: 0.0
  warmup_bias_lr: 0.1
yolov4:
  use_all_anchors: false
  object_scale: 1.0
  noobject_scale: 1.0
  class_scale: 1.0
  coord_scale: 1.0
  cls_normalizer: 1.0
  iou_normalizer: 1.0
  ignore_thresh: 0.5
  iou_thresh: 1.0
  label_smooth_eps: 0
  box_loss_type: ciou
  focalloss: false
hyp:
  adam: false
  norm: L2
  lr0: 0.001
  lrf: 0.2
  momentum: 0.9
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.9
  warmup_bias_lr: 0.0
  lr_cos: true
  lr_step:
  - 100
  - 200
  - 1000000
  hsv_h: 0.1
  hsv_s: 0.5
  hsv_v: 0.5
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipup: 0.0
  fliplr: 0.2
  mosaic: 0.0
  mixup: 0.0
  gaussianblur: 0.2
  cutcolor: 0.1
  cutout: 0.0
ssd:
  default: 1
  crop: 0
  det_crop: 0
  mosaic: 0
total_batch_size: 2
img_size:
- 576
- 960
batch_size: 2
