dic_data = {1: 'person', 2: 'bicycle', 3: 'car', 4: 'motorcycle', 5: 'airplane', 6: 'bus', 7: 'train', 8: 'truck',
           9: 'boat', 10: 'traffic light', 11: 'fire hydrant', 13: 'stop sign', 14: 'parking meter', 15: 'bench',
           16: 'bird', 17: 'cat', 18: 'dog', 19: 'horse', 20: 'sheep', 21: 'cow', 22: 'elephant', 23: 'bear', 24: 'zebra',
           25: 'giraffe', 27: 'backpack', 28: 'umbrella', 31: 'handbag', 32: 'tie', 33: 'suitcase', 34: 'frisbee',
           35: 'skis', 36: 'snowboard', 37: 'sports ball', 38: 'kite', 39: 'baseball bat', 40: 'baseball glove',
           41: 'skateboard', 42: 'surfboard', 43: 'tennis racket', 44: 'bottle', 46: 'wine glass', 47: 'cup',
           48: 'fork', 49: 'knife', 50: 'spoon', 51: 'bowl', 52: 'banana', 53: 'apple', 54: 'sandwich', 55: 'orange',
           56: 'broccoli', 57: 'carrot', 58: 'hot dog', 59: 'pizza', 60: 'donut', 61: 'cake', 62: 'chair', 63: 'couch',
           64: 'potted plant', 65: 'bed', 67: 'dining table', 70: 'toilet', 72: 'tv', 73: 'laptop', 74: 'mouse',
           75: 'remote', 76: 'keyboard', 77: 'cell phone', 78: 'microwave', 79: 'oven', 80: 'toaster', 81: 'sink',
           82: 'refrigerator', 84: 'book', 85: 'clock', 86: 'vase', 87: 'scissors', 88: 'teddy bear', 89: 'hair drier',
           90: 'toothbrush'}

ch_name = [
    '人',
'自行车',
'汽车',
'摩托车',
'飞机',
'公交车',
'火车',
'卡车',
'船',
'红绿灯',
'消防栓',
'停止标志',
'停车收费表',
'长凳',
'鸟',
'猫',
'狗',
'马',
'羊',
'牛',
'象',
'熊',
'斑马',
'长颈鹿',
'背包',
'雨伞',
'手提包',
'领带',
'手提箱',
'飞盘',
'滑雪板',
'单板滑雪',
'运动球',
'风筝',
'棒球棒',
'棒球手套',
'滑板',
'冲浪板',
'网球拍',
'瓶子',
'红酒杯',
'杯子',
'叉子',
'刀',
'勺',
'碗',
'香蕉',
'苹果',
'三明治',
'橙子',
'西兰花',
'胡萝卜',
'热狗',
'比萨',
'甜甜圈',
'蛋糕',
'椅子',
'长椅',
'盆栽',
'床',
'餐桌',
'马桶',
'电视',
'笔记本电脑',
'鼠标',
'遥控器',
'键盘',
'手机',
'微波炉',
'烤箱',
'烤面包机',
'洗碗槽',
'冰箱',
'书',
'时钟',
'花瓶',
'剪刀',
'泰迪熊',
'吹风机',
'牙刷',
]


# print(len(dic_data))
# print(len(ch_name))
# news_dic_data = {}
# news_ch_name = {}
# for i,j in zip(range(len(dic_data)),dic_data.keys()):
#     news_dic_data[dic_data[j]] = str(i) 
# print(news_dic_data)
# for i,j in zip(range(len(ch_name)),news_dic_data.keys()):
#     news_ch_name[news_dic_data[i]] = ch_name[j]
# print(news_ch_name)

s = ''
for i in range(len(dic_data)):
    s = s + str(i) +','
print(s)
